### ISSUE TITLE
artist-mode cursor misalignment

### ISSUE THREAD

**Issue by seanfarley** [doomemacs/core#2742]
**What did you expect to happen?**
In any text file with `artist-mode` enabled, the ascii art should be rendered where the cursor is.

**What actually happened?**
The ascii art is rendered four spaces to the right of the cursor.

**Additional details:**
- It seems to work correctly in vanilla emacs

**Steps to reproduce:**
1. Open text file
2. Enable `artist-mode`
3. Try to draw a rectangle or line

**Comment by seanfarley** [comment]
Aha! It's the `display-line-number-mode` that causes this. Would it be possible to have doom disable that mode for `artist-mode`?

**Comment by chengyi** [comment]
when I open text file
`display-line-number-mode` is off
but you could try:
``` emacs-lisp
(add-hook! 'artist-mode-hook
  (defun seanfarley//turnoff-line-mode ()
    (setq display-line-number-mode -1)))
```
the code just for tips, it is not tested. :rofl:

**Comment by seanfarley** [comment]
Thanks :-) And yep, I had something similar; just wondering if I should ship it upstream (though feel free to make a PR if you want the credit!)

**Comment by chengyi** [comment]
:-) we can ask @hlissner.  maybe I push a pull request later.

**Comment by hlissner** [comment]
Not quite sure where in Doom this would fit. It should be reported upstream, considering both `display-line-numbers` and `artist-mode` are built-in packages.

**Comment by seanfarley** [comment]
Yep, totally agree but not dealing with upstream is a huge benefit I get out of doom :-)

**Comment by roshanq** [comment]
I have this problem even when the display-line-number-mode is off

**Comment by seanfarley** [comment]
I've reported this upstream: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=43811

So, let's go ahead and close this since it's not actionable here :-)

**Comment by seanfarley** [comment]
FYI, this is now fixed in master: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=43811

**Comment by ksymilian** [comment]
> I have this problem even when the display-line-number-mode is off

Turning off the line number mode also didn't fix the issue for me but following the logic of disabling further, potentially conflicting modes I was able to fix the misallignment by disabling `mixed-pitch-font`!

I believe that's my first ever contribution to any project and I want to express how great `doom-emacs` is. Thank you and all the contributors!
